'--------------------------- --------------------------- ---------------------------
' Module  : clsTreeView
' Author  : paweld
' Date    : 2019-09-11
' Purpose : Universal form tree view, without ActiveX or other external controls
' Licence :
'
' Changes :
'--------------------------- --------------------------- ---------------------------
' 2019-09-11 , PD : Create
'--------------------------- --------------------------- ---------------------------
Option Compare Database
Option Explicit

Public Sub ShowTree
  'Show tree
End Sub

Public Sub INIT()
  'init parameters
End Sub
