'---------------------------------------------------------------------------------------
' Module    : clsTreeViewDefinition
' Author    : paweld
' Date      : 2021-01-28
' Purpose   : Tree View class; tree definitions
' Licence   : Free
'
' Changes:
'----------------------------------------------------------------------------------------------------------------------------------
' 2021-01-28        , PD : Create class
'----------------------------------------------------------------------------------------------------------------------------------
Option Compare Database
Option Explicit

Private Const CurrentModName = "clsTreeViewDefinition"