'---------------------------------------------------------------------------------------
' Module    : clsTreeViewWithEvent
' Author    : paweld
' Date      : 2019-09-11
' Purpose   : Tree View class to help manage events
' Licence   : Free
'
' Changes:
'----------------------------------------------------------------------------------------------------------------------------------
' 2021-01-28        , PD : Create class
'----------------------------------------------------------------------------------------------------------------------------------
Option Compare Database
Option Explicit

Private Const CurrentModName = "clsTreeViewWithEvent"